// type-extensions.d.ts

// This file is generated by Hardhat. Do not edit.
import "hardhat/types/config";
import "hardhat/types/runtime";
import "@nomicfoundation/hardhat-ethers"; // Ethers plugin types
import "@fhevm/hardhat-plugin"; // FHEVM plugin types

// Hardhat'ın ethers objesini genişletiyoruz
declare module "hardhat/types/runtime" {
  export interface HardhatRuntimeEnvironment {
    ethers: typeof import("ethers"); // ethers'ı global olarak tanıtıyoruz
  }
}

// FHEVM eklentisinin NetworkUserConfig'i genişletmesini sağlıyoruz
declare module "hardhat/types/config" {
  export interface NetworksConfig {
    fhevm?: {
      network: "dev" | "sepolia" | "zama-devnet"; // FHEVM ağ tipleri
      // Diğer FHEVM specific konfigürasyonları buraya eklenebilir
      // Şu an için sadece network yeterli
    };
  }
  export interface NetworkUserConfig {
    fhevm?: {
      network: "dev" | "sepolia" | "zama-devnet";
      // config?: { // Eğer ihtiyacımız olursa ekleriz
      //   precompiledAddresses?: any;
      // }
    };
  }
}