/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as zamaConfigSol from "./ZamaConfig.sol";
export { FHEVoting__factory } from "./FHEVoting__factory";
